Add --region param to `ecs_run.rb`
railsware/aws-ecs-tools pull request #1
Opened 2020-09-14 10:36 UTC by IgorDobryn

### issue 
I had misconfigured default region in `~/.aws/config`. This caused empty clusters list and further no cluster errors. 
By this week we allow to specify `--region` param and output what is the current region running the command.

2020-09-15 15:54 UTC, le0pard requested changes
Looks like region will not work, because you need `config[:region] = r`

2020-09-15 15:54 UTC, le0pard commented on ecs_run.rb
> +    config[:region] = true
`region` cannot by boolean

2020-09-17 08:05 UTC, IgorDobryn commented on ecs_run.rb
> +    config[:region] = true
@le0pard you're right. Actually I fixed this and just forgot to `push` it.

2020-09-22 10:07 UTC, leonid-shevtsov commented
but you can do `env AWS_REGION=xx-xxx-x ecs_run.rb`

2020-09-22 10:07 UTC, le0pard approved these changes

2020-09-22 10:08 UTC, yvasilkov approved these changes

2020-09-22 10:09 UTC, fuksito approved these changes

2020-09-22 10:46 UTC, IgorDobryn commented
> but you can do env AWS_REGION=xx-xxx-x ecs_run.rb (which is a well known built in way to configure the region)

this is what I was not aware of. Should we keep/close it?

2020-09-22 13:11 UTC, leonid-shevtsov approved these changes
I've thought about it and I guess it makes sense. Because region is kind of a part of the service URL (like `region/cluster/service`) and not just an environment or connection option.

So :+1:

2020-09-22 13:59 UTC, merged